# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mimir_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windows = QtWidgets.QGridLayout()
        self.windows.setSpacing(1)
        self.windows.setObjectName("windows")
        self.axial_window = QtWidgets.QHBoxLayout()
        self.axial_window.setSpacing(1)
        self.axial_window.setObjectName("axial_window")
        self.axial_slice_viewer = QtWidgets.QGraphicsView(self.centralwidget)
        self.axial_slice_viewer.setObjectName("axial_slice_viewer")
        self.axial_window.addWidget(self.axial_slice_viewer)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.axial_save_slice = QtWidgets.QPushButton(self.centralwidget)
        self.axial_save_slice.setEnabled(True)
        self.axial_save_slice.setMaximumSize(QtCore.QSize(18, 18))
        self.axial_save_slice.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/screenshot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.axial_save_slice.setIcon(icon)
        self.axial_save_slice.setIconSize(QtCore.QSize(12, 12))
        self.axial_save_slice.setObjectName("axial_save_slice")
        self.verticalLayout_4.addWidget(self.axial_save_slice)
        self.axial_slice_slider = QtWidgets.QSlider(self.centralwidget)
        self.axial_slice_slider.setMaximumSize(QtCore.QSize(18, 16777215))
        self.axial_slice_slider.setOrientation(QtCore.Qt.Vertical)
        self.axial_slice_slider.setObjectName("axial_slice_slider")
        self.verticalLayout_4.addWidget(self.axial_slice_slider)
        self.axial_window.addLayout(self.verticalLayout_4)
        self.windows.addLayout(self.axial_window, 0, 0, 1, 1)
        self.coronal_window = QtWidgets.QHBoxLayout()
        self.coronal_window.setSpacing(1)
        self.coronal_window.setObjectName("coronal_window")
        self.coronal_slice_viewer = QtWidgets.QGraphicsView(self.centralwidget)
        self.coronal_slice_viewer.setObjectName("coronal_slice_viewer")
        self.coronal_window.addWidget(self.coronal_slice_viewer)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.coronal_save_slice = QtWidgets.QPushButton(self.centralwidget)
        self.coronal_save_slice.setEnabled(True)
        self.coronal_save_slice.setMaximumSize(QtCore.QSize(18, 18))
        self.coronal_save_slice.setText("")
        self.coronal_save_slice.setIcon(icon)
        self.coronal_save_slice.setIconSize(QtCore.QSize(12, 12))
        self.coronal_save_slice.setObjectName("coronal_save_slice")
        self.verticalLayout_8.addWidget(self.coronal_save_slice)
        self.coronal_slice_slider = QtWidgets.QSlider(self.centralwidget)
        self.coronal_slice_slider.setMaximumSize(QtCore.QSize(18, 16777215))
        self.coronal_slice_slider.setOrientation(QtCore.Qt.Vertical)
        self.coronal_slice_slider.setObjectName("coronal_slice_slider")
        self.verticalLayout_8.addWidget(self.coronal_slice_slider)
        self.coronal_window.addLayout(self.verticalLayout_8)
        self.windows.addLayout(self.coronal_window, 1, 0, 1, 1)
        self.sagittal_window = QtWidgets.QHBoxLayout()
        self.sagittal_window.setSpacing(1)
        self.sagittal_window.setObjectName("sagittal_window")
        self.sagittal_slice_viewer = QtWidgets.QGraphicsView(self.centralwidget)
        self.sagittal_slice_viewer.setObjectName("sagittal_slice_viewer")
        self.sagittal_window.addWidget(self.sagittal_slice_viewer)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sagittal_save_slice = QtWidgets.QPushButton(self.centralwidget)
        self.sagittal_save_slice.setEnabled(True)
        self.sagittal_save_slice.setMaximumSize(QtCore.QSize(18, 18))
        self.sagittal_save_slice.setText("")
        self.sagittal_save_slice.setIcon(icon)
        self.sagittal_save_slice.setIconSize(QtCore.QSize(12, 12))
        self.sagittal_save_slice.setObjectName("sagittal_save_slice")
        self.verticalLayout_5.addWidget(self.sagittal_save_slice)
        self.sagittal_slice_slider = QtWidgets.QSlider(self.centralwidget)
        self.sagittal_slice_slider.setMaximumSize(QtCore.QSize(18, 16777215))
        self.sagittal_slice_slider.setOrientation(QtCore.Qt.Vertical)
        self.sagittal_slice_slider.setObjectName("sagittal_slice_slider")
        self.verticalLayout_5.addWidget(self.sagittal_slice_slider)
        self.sagittal_window.addLayout(self.verticalLayout_5)
        self.windows.addLayout(self.sagittal_window, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.windows)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 817, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mímir"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

