# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mimir_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windows = QtWidgets.QGridLayout()
        self.windows.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.windows.setSpacing(1)
        self.windows.setObjectName("windows")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mask_mode_button = QtWidgets.QRadioButton(self.tab)
        self.mask_mode_button.setObjectName("mask_mode_button")
        self.horizontalLayout.addWidget(self.mask_mode_button)
        self.marker_mode_button = QtWidgets.QRadioButton(self.tab)
        self.marker_mode_button.setObjectName("marker_mode_button")
        self.horizontalLayout.addWidget(self.marker_mode_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cycle_nb_label = QtWidgets.QLabel(self.tab)
        self.cycle_nb_label.setObjectName("cycle_nb_label")
        self.horizontalLayout_3.addWidget(self.cycle_nb_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.cycle_slider = QtWidgets.QSlider(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cycle_slider.sizePolicy().hasHeightForWidth())
        self.cycle_slider.setSizePolicy(sizePolicy)
        self.cycle_slider.setMinimumSize(QtCore.QSize(350, 0))
        self.cycle_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cycle_slider.setObjectName("cycle_slider")
        self.verticalLayout_6.addWidget(self.cycle_slider)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.contrast_nb_label = QtWidgets.QLabel(self.tab)
        self.contrast_nb_label.setObjectName("contrast_nb_label")
        self.horizontalLayout_4.addWidget(self.contrast_nb_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.label_2 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.min_contrast_slider = QtWidgets.QSlider(self.tab)
        self.min_contrast_slider.setMinimumSize(QtCore.QSize(350, 0))
        self.min_contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_contrast_slider.setObjectName("min_contrast_slider")
        self.verticalLayout_6.addWidget(self.min_contrast_slider)
        self.label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.max_contrast_slider = QtWidgets.QSlider(self.tab)
        self.max_contrast_slider.setMinimumSize(QtCore.QSize(350, 0))
        self.max_contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_contrast_slider.setObjectName("max_contrast_slider")
        self.verticalLayout_6.addWidget(self.max_contrast_slider)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listView = QtWidgets.QListView(self.tab_2)
        self.listView.setObjectName("listView")
        self.verticalLayout_3.addWidget(self.listView)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.windows.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.coronal_window = QtWidgets.QHBoxLayout()
        self.coronal_window.setSpacing(1)
        self.coronal_window.setObjectName("coronal_window")
        self.coronal_slice_viewer = CursorGraphicsView(self.centralwidget)
        self.coronal_slice_viewer.setObjectName("coronal_slice_viewer")
        self.coronal_window.addWidget(self.coronal_slice_viewer)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.coronal_save_slice = QtWidgets.QPushButton(self.centralwidget)
        self.coronal_save_slice.setEnabled(True)
        self.coronal_save_slice.setMaximumSize(QtCore.QSize(18, 18))
        self.coronal_save_slice.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/screenshot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coronal_save_slice.setIcon(icon)
        self.coronal_save_slice.setIconSize(QtCore.QSize(12, 12))
        self.coronal_save_slice.setObjectName("coronal_save_slice")
        self.verticalLayout_8.addWidget(self.coronal_save_slice)
        self.coronal_slice_slider = QtWidgets.QSlider(self.centralwidget)
        self.coronal_slice_slider.setMaximumSize(QtCore.QSize(18, 16777215))
        self.coronal_slice_slider.setOrientation(QtCore.Qt.Vertical)
        self.coronal_slice_slider.setObjectName("coronal_slice_slider")
        self.verticalLayout_8.addWidget(self.coronal_slice_slider)
        self.coronal_window.addLayout(self.verticalLayout_8)
        self.windows.addLayout(self.coronal_window, 1, 0, 1, 1)
        self.sagittal_window = QtWidgets.QHBoxLayout()
        self.sagittal_window.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.sagittal_window.setContentsMargins(-1, -1, 0, -1)
        self.sagittal_window.setSpacing(1)
        self.sagittal_window.setObjectName("sagittal_window")
        self.sagittal_slice_viewer = CursorGraphicsView(self.centralwidget)
        self.sagittal_slice_viewer.setObjectName("sagittal_slice_viewer")
        self.sagittal_window.addWidget(self.sagittal_slice_viewer)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sagittal_save_slice = QtWidgets.QPushButton(self.centralwidget)
        self.sagittal_save_slice.setEnabled(True)
        self.sagittal_save_slice.setMaximumSize(QtCore.QSize(18, 18))
        self.sagittal_save_slice.setText("")
        self.sagittal_save_slice.setIcon(icon)
        self.sagittal_save_slice.setIconSize(QtCore.QSize(12, 12))
        self.sagittal_save_slice.setObjectName("sagittal_save_slice")
        self.verticalLayout_5.addWidget(self.sagittal_save_slice)
        self.sagittal_slice_slider = QtWidgets.QSlider(self.centralwidget)
        self.sagittal_slice_slider.setMaximumSize(QtCore.QSize(18, 16777215))
        self.sagittal_slice_slider.setOrientation(QtCore.Qt.Vertical)
        self.sagittal_slice_slider.setObjectName("sagittal_slice_slider")
        self.verticalLayout_5.addWidget(self.sagittal_slice_slider)
        self.sagittal_window.addLayout(self.verticalLayout_5)
        self.windows.addLayout(self.sagittal_window, 0, 1, 1, 1)
        self.axial_window = QtWidgets.QHBoxLayout()
        self.axial_window.setSpacing(1)
        self.axial_window.setObjectName("axial_window")
        self.axial_slice_viewer = CursorGraphicsView(self.centralwidget)
        self.axial_slice_viewer.setObjectName("axial_slice_viewer")
        self.axial_window.addWidget(self.axial_slice_viewer)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.axial_save_slice = QtWidgets.QPushButton(self.centralwidget)
        self.axial_save_slice.setEnabled(True)
        self.axial_save_slice.setMaximumSize(QtCore.QSize(18, 18))
        self.axial_save_slice.setText("")
        self.axial_save_slice.setIcon(icon)
        self.axial_save_slice.setIconSize(QtCore.QSize(12, 12))
        self.axial_save_slice.setObjectName("axial_save_slice")
        self.verticalLayout_4.addWidget(self.axial_save_slice)
        self.axial_slice_slider = QtWidgets.QSlider(self.centralwidget)
        self.axial_slice_slider.setMaximumSize(QtCore.QSize(18, 16777215))
        self.axial_slice_slider.setOrientation(QtCore.Qt.Vertical)
        self.axial_slice_slider.setObjectName("axial_slice_slider")
        self.verticalLayout_4.addWidget(self.axial_slice_slider)
        self.axial_window.addLayout(self.verticalLayout_4)
        self.windows.addLayout(self.axial_window, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.windows)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mímir"))
        self.mask_mode_button.setText(_translate("MainWindow", "Mask"))
        self.marker_mode_button.setText(_translate("MainWindow", "Marker"))
        self.label_3.setText(_translate("MainWindow", "Cycle: "))
        self.cycle_nb_label.setText(_translate("MainWindow", "0 / 0"))
        self.label_6.setText(_translate("MainWindow", "Contrast min | max: "))
        self.contrast_nb_label.setText(_translate("MainWindow", "0% | 0%"))
        self.label_2.setText(_translate("MainWindow", "Min contrast"))
        self.label.setText(_translate("MainWindow", "Max contrast"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Points"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

from CursorGraphicsView import CursorGraphicsView
