# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mimir_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windows = QtWidgets.QGridLayout()
        self.windows.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.windows.setSpacing(1)
        self.windows.setObjectName("windows")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMenu.setObjectName("tabMenu")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mainTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cycle_nb_label = QtWidgets.QLabel(self.mainTab)
        self.cycle_nb_label.setObjectName("cycle_nb_label")
        self.horizontalLayout_3.addWidget(self.cycle_nb_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.cycle_slider = QtWidgets.QSlider(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cycle_slider.sizePolicy().hasHeightForWidth())
        self.cycle_slider.setSizePolicy(sizePolicy)
        self.cycle_slider.setMinimumSize(QtCore.QSize(350, 0))
        self.cycle_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cycle_slider.setObjectName("cycle_slider")
        self.verticalLayout_6.addWidget(self.cycle_slider)
        self.comboBox = QtWidgets.QComboBox(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.contrast_nb_label = QtWidgets.QLabel(self.mainTab)
        self.contrast_nb_label.setObjectName("contrast_nb_label")
        self.horizontalLayout_4.addWidget(self.contrast_nb_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.label_2 = QtWidgets.QLabel(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.min_contrast_slider = QtWidgets.QSlider(self.mainTab)
        self.min_contrast_slider.setMinimumSize(QtCore.QSize(350, 0))
        self.min_contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_contrast_slider.setObjectName("min_contrast_slider")
        self.verticalLayout_6.addWidget(self.min_contrast_slider)
        self.label = QtWidgets.QLabel(self.mainTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.max_contrast_slider = QtWidgets.QSlider(self.mainTab)
        self.max_contrast_slider.setMinimumSize(QtCore.QSize(350, 0))
        self.max_contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_contrast_slider.setObjectName("max_contrast_slider")
        self.verticalLayout_6.addWidget(self.max_contrast_slider)
        self.tabMenu.addTab(self.mainTab, "")
        self.pointsTab = QtWidgets.QWidget()
        self.pointsTab.setObjectName("pointsTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pointsTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addPointBt = QtWidgets.QPushButton(self.pointsTab)
        self.addPointBt.setObjectName("addPointBt")
        self.horizontalLayout_2.addWidget(self.addPointBt)
        self.delPointBt = QtWidgets.QPushButton(self.pointsTab)
        self.delPointBt.setObjectName("delPointBt")
        self.horizontalLayout_2.addWidget(self.delPointBt)
        self.savePointsBt = QtWidgets.QPushButton(self.pointsTab)
        self.savePointsBt.setObjectName("savePointsBt")
        self.horizontalLayout_2.addWidget(self.savePointsBt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.pointsList = QtWidgets.QListView(self.pointsTab)
        self.pointsList.setObjectName("pointsList")
        self.verticalLayout_3.addWidget(self.pointsList)
        self.tabMenu.addTab(self.pointsTab, "")
        self.masksTab = QtWidgets.QWidget()
        self.masksTab.setObjectName("masksTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.masksTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addMaskBt = QtWidgets.QPushButton(self.masksTab)
        self.addMaskBt.setObjectName("addMaskBt")
        self.horizontalLayout_5.addWidget(self.addMaskBt)
        self.delMaskBt = QtWidgets.QPushButton(self.masksTab)
        self.delMaskBt.setObjectName("delMaskBt")
        self.horizontalLayout_5.addWidget(self.delMaskBt)
        self.saveMasksBt = QtWidgets.QPushButton(self.masksTab)
        self.saveMasksBt.setObjectName("saveMasksBt")
        self.horizontalLayout_5.addWidget(self.saveMasksBt)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.masksList = QtWidgets.QTableView(self.masksTab)
        self.masksList.setObjectName("masksList")
        self.verticalLayout_7.addWidget(self.masksList)
        self.tabMenu.addTab(self.masksTab, "")
        self.verticalLayout_2.addWidget(self.tabMenu)
        self.windows.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.coronal_window = QtWidgets.QHBoxLayout()
        self.coronal_window.setSpacing(1)
        self.coronal_window.setObjectName("coronal_window")
        self.coronal_slice_viewer = CursorGraphicsView(self.centralwidget)
        self.coronal_slice_viewer.setObjectName("coronal_slice_viewer")
        self.coronal_window.addWidget(self.coronal_slice_viewer)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.coronal_save_slice = QtWidgets.QPushButton(self.centralwidget)
        self.coronal_save_slice.setEnabled(True)
        self.coronal_save_slice.setMaximumSize(QtCore.QSize(18, 18))
        self.coronal_save_slice.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/screenshot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coronal_save_slice.setIcon(icon)
        self.coronal_save_slice.setIconSize(QtCore.QSize(12, 12))
        self.coronal_save_slice.setObjectName("coronal_save_slice")
        self.verticalLayout_8.addWidget(self.coronal_save_slice)
        self.coronal_slice_slider = QtWidgets.QSlider(self.centralwidget)
        self.coronal_slice_slider.setMaximumSize(QtCore.QSize(18, 16777215))
        self.coronal_slice_slider.setOrientation(QtCore.Qt.Vertical)
        self.coronal_slice_slider.setObjectName("coronal_slice_slider")
        self.verticalLayout_8.addWidget(self.coronal_slice_slider)
        self.coronal_window.addLayout(self.verticalLayout_8)
        self.windows.addLayout(self.coronal_window, 1, 0, 1, 1)
        self.sagittal_window = QtWidgets.QHBoxLayout()
        self.sagittal_window.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.sagittal_window.setContentsMargins(-1, -1, 0, -1)
        self.sagittal_window.setSpacing(1)
        self.sagittal_window.setObjectName("sagittal_window")
        self.sagittal_slice_viewer = CursorGraphicsView(self.centralwidget)
        self.sagittal_slice_viewer.setObjectName("sagittal_slice_viewer")
        self.sagittal_window.addWidget(self.sagittal_slice_viewer)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sagittal_save_slice = QtWidgets.QPushButton(self.centralwidget)
        self.sagittal_save_slice.setEnabled(True)
        self.sagittal_save_slice.setMaximumSize(QtCore.QSize(18, 18))
        self.sagittal_save_slice.setText("")
        self.sagittal_save_slice.setIcon(icon)
        self.sagittal_save_slice.setIconSize(QtCore.QSize(12, 12))
        self.sagittal_save_slice.setObjectName("sagittal_save_slice")
        self.verticalLayout_5.addWidget(self.sagittal_save_slice)
        self.sagittal_slice_slider = QtWidgets.QSlider(self.centralwidget)
        self.sagittal_slice_slider.setMaximumSize(QtCore.QSize(18, 16777215))
        self.sagittal_slice_slider.setOrientation(QtCore.Qt.Vertical)
        self.sagittal_slice_slider.setObjectName("sagittal_slice_slider")
        self.verticalLayout_5.addWidget(self.sagittal_slice_slider)
        self.sagittal_window.addLayout(self.verticalLayout_5)
        self.windows.addLayout(self.sagittal_window, 0, 1, 1, 1)
        self.axial_window = QtWidgets.QHBoxLayout()
        self.axial_window.setSpacing(1)
        self.axial_window.setObjectName("axial_window")
        self.axial_slice_viewer = CursorGraphicsView(self.centralwidget)
        self.axial_slice_viewer.setObjectName("axial_slice_viewer")
        self.axial_window.addWidget(self.axial_slice_viewer)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.axial_save_slice = QtWidgets.QPushButton(self.centralwidget)
        self.axial_save_slice.setEnabled(True)
        self.axial_save_slice.setMaximumSize(QtCore.QSize(18, 18))
        self.axial_save_slice.setText("")
        self.axial_save_slice.setIcon(icon)
        self.axial_save_slice.setIconSize(QtCore.QSize(12, 12))
        self.axial_save_slice.setObjectName("axial_save_slice")
        self.verticalLayout_4.addWidget(self.axial_save_slice)
        self.axial_slice_slider = QtWidgets.QSlider(self.centralwidget)
        self.axial_slice_slider.setMaximumSize(QtCore.QSize(18, 16777215))
        self.axial_slice_slider.setOrientation(QtCore.Qt.Vertical)
        self.axial_slice_slider.setObjectName("axial_slice_slider")
        self.verticalLayout_4.addWidget(self.axial_slice_slider)
        self.axial_window.addLayout(self.verticalLayout_4)
        self.windows.addLayout(self.axial_window, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.windows)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuPoint = QtWidgets.QMenu(self.menuBar)
        self.menuPoint.setObjectName("menuPoint")
        self.menuMask = QtWidgets.QMenu(self.menuBar)
        self.menuMask.setObjectName("menuMask")
        self.menuScreenshot = QtWidgets.QMenu(self.menuBar)
        self.menuScreenshot.setObjectName("menuScreenshot")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionNew_point = QtWidgets.QAction(MainWindow)
        self.actionNew_point.setObjectName("actionNew_point")
        self.actionDelete_point = QtWidgets.QAction(MainWindow)
        self.actionDelete_point.setObjectName("actionDelete_point")
        self.actionNew_mask = QtWidgets.QAction(MainWindow)
        self.actionNew_mask.setObjectName("actionNew_mask")
        self.actionDelete_mask = QtWidgets.QAction(MainWindow)
        self.actionDelete_mask.setObjectName("actionDelete_mask")
        self.actionSave_points_masks = QtWidgets.QAction(MainWindow)
        self.actionSave_points_masks.setObjectName("actionSave_points_masks")
        self.actionLoad_points_masks = QtWidgets.QAction(MainWindow)
        self.actionLoad_points_masks.setObjectName("actionLoad_points_masks")
        self.actionSave_current_sagittal_slice = QtWidgets.QAction(MainWindow)
        self.actionSave_current_sagittal_slice.setObjectName("actionSave_current_sagittal_slice")
        self.actionSave_current_coronal_slice = QtWidgets.QAction(MainWindow)
        self.actionSave_current_coronal_slice.setObjectName("actionSave_current_coronal_slice")
        self.actionSave_current_axial_slice = QtWidgets.QAction(MainWindow)
        self.actionSave_current_axial_slice.setObjectName("actionSave_current_axial_slice")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_points_masks)
        self.menuFile.addAction(self.actionLoad_points_masks)
        self.menuPoint.addAction(self.actionNew_point)
        self.menuPoint.addAction(self.actionDelete_point)
        self.menuMask.addAction(self.actionNew_mask)
        self.menuMask.addAction(self.actionDelete_mask)
        self.menuScreenshot.addAction(self.actionSave_current_sagittal_slice)
        self.menuScreenshot.addAction(self.actionSave_current_coronal_slice)
        self.menuScreenshot.addAction(self.actionSave_current_axial_slice)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuPoint.menuAction())
        self.menuBar.addAction(self.menuMask.menuAction())
        self.menuBar.addAction(self.menuScreenshot.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mímir"))
        self.label_3.setText(_translate("MainWindow", "Cycle: "))
        self.cycle_nb_label.setText(_translate("MainWindow", "0 / 0"))
        self.label_6.setText(_translate("MainWindow", "Contrast min | max: "))
        self.contrast_nb_label.setText(_translate("MainWindow", "0% | 0%"))
        self.label_2.setText(_translate("MainWindow", "Min contrast"))
        self.label.setText(_translate("MainWindow", "Max contrast"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.mainTab), _translate("MainWindow", "Main"))
        self.addPointBt.setText(_translate("MainWindow", "+"))
        self.delPointBt.setText(_translate("MainWindow", "-"))
        self.savePointsBt.setText(_translate("MainWindow", "Save points"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.pointsTab), _translate("MainWindow", "Points"))
        self.addMaskBt.setText(_translate("MainWindow", "+"))
        self.delMaskBt.setText(_translate("MainWindow", "-"))
        self.saveMasksBt.setText(_translate("MainWindow", "Save masks"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.masksTab), _translate("MainWindow", "Masks"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPoint.setTitle(_translate("MainWindow", "Point"))
        self.menuMask.setTitle(_translate("MainWindow", "Mask"))
        self.menuScreenshot.setTitle(_translate("MainWindow", "Screenshot"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionNew_point.setText(_translate("MainWindow", "New point"))
        self.actionDelete_point.setText(_translate("MainWindow", "Delete point"))
        self.actionNew_mask.setText(_translate("MainWindow", "New mask"))
        self.actionDelete_mask.setText(_translate("MainWindow", "Delete mask"))
        self.actionSave_points_masks.setText(_translate("MainWindow", "Save points/masks"))
        self.actionLoad_points_masks.setText(_translate("MainWindow", "Load points/masks"))
        self.actionSave_current_sagittal_slice.setText(_translate("MainWindow", "Save current sagittal slice"))
        self.actionSave_current_coronal_slice.setText(_translate("MainWindow", "Save current coronal slice"))
        self.actionSave_current_axial_slice.setText(_translate("MainWindow", "Save current axial slice"))

from CursorGraphicsView import CursorGraphicsView
